const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const root=path.resolve(__dirname,'..');const context={window:{fetch:async()=>{throw new Error('Unexpected fetch');}},document:{getElementById(){return null},createElement(){return{textContent:'',style:{},appendChild(){}}},head:{appendChild(){}}},MutationObserver:class{observe(){}},setTimeout,clearTimeout,Promise};vm.createContext(context);for(const f of ['questions.js','classes.js','project-enhancements.js','fairness-calibration.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f});const W=context.window,Q=W.QUIZ_QUESTIONS,C=W.CLASS_DATA,D=Object.keys(W.QUIZ_DIMS).filter(d=>d!=='__neutral_prior'),DW=W.QUIZ_DIM_WEIGHTS,QW=W.QUIZ_QUESTION_WEIGHTS,V=W.QUIZ_OPTION_VECTORS,K=Object.keys(C);for(const c of Object.values(C))delete c.dims.__neutral_prior;
function nv(s){return Object.fromEntries(D.map(d=>[d,typeof s?.[d]==='number'?s[d]:.5]));}function pref(q,letters){const a=Object.fromEntries(D.map(d=>[d,.5])),e=Object.fromEntries(D.map(d=>[d,0]));letters.forEach((letter,rank)=>{const p=nv(V[q.id][letter.charCodeAt(0)-65]),w=Number(QW[q.id]??1)*([1,.72,.5,.34][rank]??.25);D.forEach(d=>{const sig=Math.abs(p[d]-.5)*2;if(sig<.08)return;const c=w*sig,b=c/(e[d]+c+.0001);a[d]=a[d]*(1-b)+p[d]*b;e[d]+=c;});});return{a,e};}
function scoreRow(ans){const u=Object.fromEntries(D.map(d=>[d,.5])),ew=Object.fromEntries(D.map(d=>[d,0]));ans.forEach((letters,i)=>{const{a,e}=pref(Q[i],letters);D.forEach(d=>{if(!e[d])return;const n=ew[d]+e[d];u[d]=ew[d]?(u[d]*ew[d]+a[d]*e[d])/n:a[d];ew[d]=n;});});const out={};for(const k of K){let s=0;for(const d of D){if(!ew[d])continue;const w=(DW[d]||1)*ew[d];s+=(1-Math.min(1,Math.abs(u[d]-C[k].dims[d])))*w;}out[k]=s;}return out;}
let seed=0x9e3779b9;function rnd(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/0x100000000;}const N=10000,S=Array.from({length:N},()=>Q.map(()=>[String.fromCharCode(65+Math.floor(rnd()*4))])),rows=S.map(scoreRow);const pars={};for(const k of K){let mean=0;for(const r of rows)mean+=r[k];mean/=N;let v=0;for(const r of rows)v+=(r[k]-mean)**2;pars[k]={mean,sd:Math.sqrt(v/N)||1};}
function counts(o){const c=Object.fromEntries(K.map(k=>[k,0]));for(const r of rows){let bk=K[0],bv=(r[bk]-pars[bk].mean)/pars[bk].sd+o[bk];for(let i=1;i<K.length;i++){const k=K[i],v=(r[k]-pars[k].mean)/pars[k].sd+o[k];if(v>bv){bv=v;bk=k;}}c[bk]++;}return c;}function loss(c){return K.reduce((s,k)=>s+(c[k]-1000)**2,0);}
let o={fighter:.0138,page:-.2515,spearman:.3035,fp:.0503,il:-.028,cleric:-.5167,hunter:.2008,crossbow:.2615,assassin:.2046,bandit:.1288};let c=counts(o),L=loss(c);console.log('START',JSON.stringify(c),'LOSS',L);
for(let round=0;round<600&&L>0;round++){let bestO=null,bestC=null,bestL=L;for(let trial=0;trial<24;trial++){const candidate={...o};const changes=2+(rnd()*4|0);for(let j=0;j<changes;j++){const k=K[(rnd()*K.length)|0];const mag=(.00005+Math.pow(rnd(),2)*.002)*(rnd()<.5?-1:1);candidate[k]+=mag;}const cc=counts(candidate),ll=loss(cc);if(ll<bestL){bestL=ll;bestO=candidate;bestC=cc;}}
if(bestO){o=bestO;c=bestC;L=bestL;}else{const k=K[(rnd()*K.length)|0];o[k]+=(rnd()<.5?-1:1)*.0001;const cc=counts(o),ll=loss(cc);if(ll<=L){c=cc;L=ll;}else o[k]+=(rnd()<.5?-1:1)*.0001;}
if(round%25===0||L===0)console.log('ROUND',round,'LOSS',L,'COUNTS',JSON.stringify(c),'OFFSETS',JSON.stringify(o));}
console.log('FINAL_OFFSETS',JSON.stringify(o));console.log('FINAL_COUNTS',JSON.stringify(c));