const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const root=path.resolve(__dirname,'..');const context={window:{fetch:async()=>{throw new Error('Unexpected fetch');}},document:{getElementById(){return null},createElement(){return{textContent:'',style:{},appendChild(){}}},head:{appendChild(){}}},MutationObserver:class{observe(){}},setTimeout,clearTimeout,Promise};vm.createContext(context);for(const f of ['questions.js','classes.js','project-enhancements.js','fairness-calibration.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f});const W=context.window,Q=W.QUIZ_QUESTIONS,C=W.CLASS_DATA,D=Object.keys(W.QUIZ_DIMS).filter(d=>d!=='__neutral_prior'),DW=W.QUIZ_DIM_WEIGHTS,QW=W.QUIZ_QUESTION_WEIGHTS,V=W.QUIZ_OPTION_VECTORS,K=Object.keys(C);for(const c of Object.values(C))delete c.dims.__neutral_prior;
function nv(s){return Object.fromEntries(D.map(d=>[d,typeof s?.[d]==='number'?s[d]:.5]));}function pref(q,letters){const a=Object.fromEntries(D.map(d=>[d,.5])),e=Object.fromEntries(D.map(d=>[d,0]));letters.forEach((letter,rank)=>{const p=nv(V[q.id][letter.charCodeAt(0)-65]),w=Number(QW[q.id]??1)*([1,.72,.5,.34][rank]??.25);D.forEach(d=>{const sig=Math.abs(p[d]-.5)*2;if(sig<.08)return;const c=w*sig,b=c/(e[d]+c+.0001);a[d]=a[d]*(1-b)+p[d]*b;e[d]+=c;});});return{a,e};}
function scoreRow(ans){const u=Object.fromEntries(D.map(d=>[d,.5])),ew=Object.fromEntries(D.map(d=>[d,0]));ans.forEach((letters,i)=>{const{a,e}=pref(Q[i],letters);D.forEach(d=>{if(!e[d])return;const n=ew[d]+e[d];u[d]=ew[d]?(u[d]*ew[d]+a[d]*e[d])/n:a[d];ew[d]=n;});});const out={};for(const k of K){let s=0;for(const d of D){if(!ew[d])continue;const w=(DW[d]||1)*ew[d];s+=(1-Math.min(1,Math.abs(u[d]-C[k].dims[d])))*w;}out[k]=s;}return out;}
let seed=0x9e3779b9;function rnd(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/0x100000000;}const N=10000,S=Array.from({length:N},()=>Q.map(()=>[String.fromCharCode(65+Math.floor(rnd()*4))])),rows=S.map(scoreRow);
const pars={};for(const k of K){const vals=rows.map(r=>r[k]);const mean=vals.reduce((a,b)=>a+b,0)/N;const variance=vals.reduce((a,b)=>a+(b-mean)**2,0)/N;pars[k]={mean,sd:Math.sqrt(variance)||1};}
function counts(offsets){const c=Object.fromEntries(K.map(k=>[k,0]));for(const r of rows){let bk=K[0],bv=(r[bk]-pars[bk].mean)/pars[bk].sd+offsets[bk];for(let i=1;i<K.length;i++){const k=K[i],v=(r[k]-pars[k].mean)/pars[k].sd+offsets[k];if(v>bv){bv=v;bk=k;}}c[bk]++;}return c;}function loss(c){return K.reduce((s,k)=>s+(c[k]-1000)**2,0);}
let offsets=Object.fromEntries(K.map(k=>[k,0])),best=counts(offsets),L=loss(best);console.log('STANDARDIZED_START',JSON.stringify(best),'LOSS',L);
for(let pass=0;pass<30&&L>0;pass++){let changed=false;for(const k of K){let local=offsets[k],localC=best,localL=L;for(const step of[.1,.05,.02,.01,.005,.002,.001,.0005,.0002,.0001]){for(const dir of[1,-1]){const x=local+dir*step;offsets[k]=x;const c=counts(offsets),l=loss(c);if(l<localL){local=x;localC=c;localL=l;}}offsets[k]=local;}if(localL<L){offsets[k]=local;best=localC;L=localL;changed=true;}else offsets[k]=local;}
console.log('PASS',pass,'LOSS',L,'COUNTS',JSON.stringify(best),'OFFSETS',JSON.stringify(offsets));if(!changed)break;}
console.log('FINAL_OFFSETS',JSON.stringify(offsets));console.log('FINAL_COUNTS',JSON.stringify(best));